In [51]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import LinearSVC

In [52]:
df = pd.read_csv("./data/heart-disease.csv")

In [53]:
x = df.drop(["target"], axis=1)
y = df["target"]

# np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [54]:
model_svc = LinearSVC()

model_svc.fit(X_train, y_train)
model_svc.score(X_test, y_test)

model_svc.predict(X_test)

c:\Users\danie\_data\courses\machine-learning-and-data-science\09-scikitlearn\env\Lib\site-packages\sklearn\svm\_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


array([1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1], dtype=int64)

In [55]:
model_knn = KNeighborsClassifier()

model_knn.fit(X_train, y_train)
model_knn.score(X_test, y_test)

model_knn.predict(X_test)

array([1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [56]:
model_forest = RandomForestClassifier()

model_forest.fit(X_train, y_train)
model_forest.score(X_test, y_test)

0.8360655737704918

In [57]:
# predict()

prediction = model_forest.predict(X_test)
labels = np.array(y_test)
score = np.mean(prediction == labels)
score

0.8360655737704918

In [59]:
# predict_proba()

prediction_probabilities = model_forest.predict_proba(X_test)
prediction_probabilities

array([[0.01, 0.99],
       [0.7 , 0.3 ],
       [0.78, 0.22],
       [0.23, 0.77],
       [0.02, 0.98],
       [0.93, 0.07],
       [0.43, 0.57],
       [0.91, 0.09],
       [0.42, 0.58],
       [0.56, 0.44],
       [0.54, 0.46],
       [0.11, 0.89],
       [0.02, 0.98],
       [0.27, 0.73],
       [0.05, 0.95],
       [0.76, 0.24],
       [0.03, 0.97],
       [0.29, 0.71],
       [0.47, 0.53],
       [0.21, 0.79],
       [0.44, 0.56],
       [0.19, 0.81],
       [0.98, 0.02],
       [0.3 , 0.7 ],
       [0.53, 0.47],
       [0.57, 0.43],
       [0.38, 0.62],
       [0.03, 0.97],
       [0.4 , 0.6 ],
       [0.  , 1.  ],
       [0.87, 0.13],
       [0.3 , 0.7 ],
       [0.25, 0.75],
       [0.19, 0.81],
       [0.19, 0.81],
       [0.96, 0.04],
       [0.87, 0.13],
       [0.77, 0.23],
       [0.62, 0.38],
       [0.73, 0.27],
       [0.92, 0.08],
       [0.99, 0.01],
       [0.33, 0.67],
       [0.08, 0.92],
       [0.46, 0.54],
       [0.3 , 0.7 ],
       [0.24, 0.76],
       [0.71,